blogs/urls.py
from django.conf.urls import url, patterns


urlpatterns = patterns("",
    url(r'^contactUs/$', "blogs.views.contact_us", name="contact_us"),
    url(r'^register/$', "blogs.views.sign_up", name="register"),
    url(r'^login/$', "blogs.views.sign_in", name="login"),
    url(r'^logout/$', "blogs.views.sign_out", name="logout"),
    url(r'^add_post/$', "blogs.views.add_post", name="add_post"),
    url(r'^delete_post/(?P<post_pk>\d+)$', "blogs.views.delete_post", name="delete_post"),
    url(r'^manage_posts/$', "blogs.views.manage_post", name="manage_posts"),
    url(r'^update/(?P<post_pk>\d+)/$', "blogs.views.update_post", name="update_post"),
    url(r'^$', "blogs.views.blog_index", name="home"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', "blogs.views.blog_post_detail", name="blog_post"),
    url(r'^post/(?P<post_pk>\d+)/$', "blogs.views.blog_post_detail", name="blog_post_pk"),
    url(r'^(?P<section_slug>[-\w]+)/$', "blogs.views.blog_section_list", name="blog_section"),
)

practical_exam/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin

urlpatterns = patterns(
    "",
    url(r"^admin/", include(admin.site.urls)),
    url(r"", include("blogs.urls")),
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
# -*- coding: utf8 -*-
import json
import urllib2

from datetime import datetime

from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from django.contrib.sites.models import Site

try:
    import twitter
except ImportError:
    twitter = None

from blogs.managers import PostManager
from blogs.settings import MARKUP_CHOICES
from blogs.utils import can_tweet



class Section(models.Model):
    name = models.CharField(max_length=140)
    slug = models.SlugField()

    def __unicode__(self):
        return self.name


class Post(models.Model):
    section = models.ForeignKey(Section, related_name="posts")
    
    title = models.CharField(max_length=90)
    slug = models.SlugField()
    author = models.ForeignKey(User, related_name="posts")
    
    markup = models.CharField(max_length=25, choices=MARKUP_CHOICES)
    
    teaser_html = models.TextField(editable=False)
    content_html = models.TextField(editable=False
        )
    
    tweet_text = models.CharField(max_length=140, editable=False)
    
    created = models.DateTimeField(default=datetime.now, editable=False) # when first revision was created
    updated = models.DateTimeField(null=True, blank=True, editable=False) # when last revision was create (even if not published)
    published = models.DateTimeField(null=True, blank=True, editable=False) # when last published
    
    view_count = models.IntegerField(default=0, editable=False)

    def rev(self, rev_id):
        return self.revisions.get(pk=rev_id)
    
    def current(self):
        "the currently visible (latest published) revision"
        return self.revisions.exclude(published=None).order_by("-published")[0]
    
    def latest(self):
        "the latest modified (even if not published) revision"
        try:
            return self.revisions.order_by("-updated")[0]
        except IndexError:
            return None
    
    class Meta:
        ordering = ("-published",)
        get_latest_by = "published"
    
    objects = PostManager()
    
    def __unicode__(self):
        return self.title
    
    def as_tweet(self):
        if not self.tweet_text:
            current_site = Site.objects.get_current()
            api_url = "http://api.tr.im/api/trim_url.json"
            u = urllib2.urlopen("%s?url=http://%s%s" % (
                api_url,
                current_site.domain,
                self.get_absolute_url(),
            ))
            result = json.loads(u.read())
            self.tweet_text = u"%s %s — %s" % (
                settings.TWITTER_TWEET_PREFIX,
                self.title,
                result["url"],
            )
        return self.tweet_text
    
    def tweet(self):
        if can_tweet():
            account = twitter.Api(
                username = settings.TWITTER_USERNAME,
                password = settings.TWITTER_PASSWORD,
            )
            account.PostUpdate(self.as_tweet())
        else:
            raise ImproperlyConfigured("Unable to send tweet due to either "
                "missing python-twitter or required settings.")
    
    def save(self, **kwargs):
        self.updated_at = datetime.now()
        super(Post, self).save(**kwargs)
    
    def get_absolute_url(self):
        if self.published:
            name = "blog_post"
            kwargs = {
                "year": self.published.strftime("%Y"),
                "month": self.published.strftime("%m"),
                "day": self.published.strftime("%d"),
                "slug": self.slug,
            }
        else:
            name = "blog_post_pk"
            kwargs = {
                "post_pk": self.pk,
            }
        return reverse(name, kwargs=kwargs)
    
    def inc_views(self):
        self.view_count += 1
        self.save()
        self.current().inc_views()


class Revision(models.Model):
    
    post = models.ForeignKey(Post, related_name="revisions")
    
    title = models.CharField(max_length=90)
    teaser = models.TextField()
    
    content = models.TextField()
    
    author = models.ForeignKey(User, related_name="revisions")
    
    updated = models.DateTimeField(default=datetime.now)
    published = models.DateTimeField(null=True, blank=True)
    
    view_count = models.IntegerField(default=0, editable=False)
    
    def __unicode__(self):
        return 'Revision %s for %s' % (self.updated.strftime('%Y%m%d-%H%M'), self.post.slug)
    
    def inc_views(self):
        self.view_count += 1
        self.save()


class Image(models.Model):
    
    post = models.ForeignKey(Post, related_name="images")
    
    image_path = models.ImageField(upload_to="images/%Y/%m/%d")
    url = models.CharField(max_length=150, blank=True)
    
    timestamp = models.DateTimeField(default=datetime.now, editable=False)
    
    def __unicode__(self):
        if self.pk is not None:
            return "{{ %d }}" % self.pk
        else:
            return "deleted image"


class FeedHit(models.Model):
    
    request_data = models.TextField()
    created = models.DateTimeField(default=datetime.now)

class ContactUs(models.Model):
    sender = models.EmailField()
    subject = models.CharField(max_length = 100)
    message = models.TextField()
    cc_myself = models.BooleanField()

blogs/views.py
from datetime import datetime

from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404, render
from django.template import RequestContext
from django.template.loader import render_to_string
from django.utils import simplejson as json
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.forms.models import modelformset_factory

from blogs.models import FeedHit, Post, Section, Revision
from blogs.forms import AdminPostForm, ContactUsForm, SignUp, SignIn, AddNewPost
from blogs.settings import ALL_SECTION_NAME
from blogs.signals import post_viewed


@login_required(login_url = "login/")
def blog_index(request):
    user = request.user
    sections = Section.objects.all()
    posts = Post.objects.filter(author_id = user.id)
    
    return render_to_response("blogs/blog_list.html", {
        "posts": posts,
        "sections": sections,
    }, context_instance=RequestContext(request))

@login_required(login_url = "login/")
def blog_section_list(request, section_slug):
    sections = Section.objects.all()
    section = get_object_or_404(Section, slug=section_slug)
    user = request.user
    if section.id is not 4:
        posts = Post.objects.filter(author_id = user.id).filter(section = section.id)
    else:
        posts = Post.objects.filter(author_id = user.id)
    return render_to_response("blogs/blog_section_list.html", {
        "section_slug": section_slug,
        "section_name": section.name,
        "posts": posts,
        "sections": sections,
    }, context_instance=RequestContext(request))

@login_required(login_url = "login/")
def blog_post_detail(request, **kwargs):
    sections = Section.objects.all()
    if "post_pk" in kwargs:
        if request.user.is_authenticated() and request.user.is_staff:
            queryset = Post.objects.all()
            post = get_object_or_404(queryset, pk=kwargs["post_pk"])
        else:
            raise Http404()
    else:
        queryset = Post.objects.current()
        queryset = queryset.filter(
            published__year = int(kwargs["year"]),
            published__month = int(kwargs["month"]),
            published__day = int(kwargs["day"]),
        )
        post = get_object_or_404(queryset, slug=kwargs["slug"])
        post_viewed.send(sender=post, post=post, request=request)
    
    return render_to_response("blogs/blog_post.html", {
        "post": post,
        "sections": sections,
    }, context_instance=RequestContext(request))


def serialize_request(request):
    data = {
        "path": request.path,
        "META": {
            "QUERY_STRING": request.META.get("QUERY_STRING"),
            "REMOTE_ADDR": request.META.get("REMOTE_ADDR"),
        }
    }
    for key in request.META:
        if key.startswith("HTTP"):
            data["META"][key] = request.META[key]
    return json.dumps(data)


def blog_feed(request, section=None):
    sections = Section.objects.all()
    section = get_object_or_404(Section, slug=section)
    posts = Post.objects.filter(section=section)

    if section is None:
        section = Section.objects.values_list('name', flat=True).order_by('name')

    current_site = Site.objects.get_current()
    
    feed_title = "%s Blog: %s" % (current_site.name, section[0].upper() + section[1:])
    
    blog_url = "http://%s%s" % (current_site.domain, reverse("blog"))
    
    url_name, kwargs = "blog_feed", {"section": section}
    feed_url = "http://%s%s" % (current_site.domain, reverse(url_name, kwargs=kwargs))
    
    if posts:
        feed_updated = posts[0].published
    else:
        feed_updated = datetime(2009, 8, 1, 0, 0, 0)
    
    # create a feed hit
    hit = FeedHit()
    hit.request_data = serialize_request(request)
    hit.save()
    
    atom = render_to_string("blogs/atom_feed.xml", {
        "feed_id": feed_url,
        "feed_title": feed_title,
        "blog_url": blog_url,
        "feed_url": feed_url,
        "feed_updated": feed_updated,
        "entries": posts,
        "current_site": current_site,
        "sections": sections,
    })
    return HttpResponse(atom, mimetype="application/atom+xml")

def contact_us(request):
    sections = Section.objects.all()
    if request.method == "POST":
        form = ContactUsForm(request.POST)
        if form.is_valid():
            sender = form.cleaned_data["sender"]
            subject = form.cleaned_data["subject"]
            message = form.cleaned_data["message"]
            cc_myself = form.cleaned_data["cc_myself"]

            recepients = ["jvdagaang@live.com.ph"]

            if cc_myself:
                recepients.append(sender)

            send_mail(subject, message, sender, recepients)
        HttpResponseRedirect("/")
    else:
        form = ContactUsForm()

    return render(request, "blogs/blog_contact_us.html",{
                "form": form,
                "sections": sections,
        })

def sign_up(request):
    sections = Section.objects.all()
    if request.method == "POST":
        form = SignUp(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            email = form.cleaned_data["email"]
            new_user = User.objects.create_user(username, email, password)
            new_user.first_name = form.cleaned_data["firstname"]
            new_user.last_name = form.cleaned_data["lastname"]
            new_user.save()

        return HttpResponseRedirect("/")
    else:
        form = SignUp()

    return render(request, "blogs/blog_sign_up.html",{"form": form,"sections":sections})

def sign_in(request):
    sections = Section.objects.all()
    if request.method == "POST":
        form = SignIn(request.POST)
        if form.is_valid():
            un = form.cleaned_data["username"]
            pw = form.cleaned_data["password"]

            user = authenticate(username = un, password = pw)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect("/")
                else:
                    return HttpResponseRedirect("sign_in/")
            else:
                return HttpResponseRedirect("sign_in/")
    else:
        form = SignIn()

    return render(request, "blogs/blog_sign_in.html", {"form": form, "sections": sections})

def sign_out(request):
    logout(request)
    return HttpResponseRedirect("/")

def add_post(request):
    sections = Section.objects.all()
    if request.method == "POST":
        form = AddNewPost(request.POST)
        if form.is_valid():
            post_slug = form.cleaned_data["title"]
            post_slug = post_slug.lower().replace(" ", "-")
            form.slug - post_slug

            form.author_id = request.user

            form.save()
            return HttpResponseRedirect("/")
        else:
            pass
    else:
        form = AddNewPost()

    return render(request, "blogs/blog_add_post.html", {"form": form, "sections": sections})

def manage_post(request):
    sections = Section.objects.all()
    user = request.user
    posts = Post.objects.filter(author_id = user.id)

    return render(request, "blogs/blog_manage_posts.html", {"sections": sections, "posts": posts})

def delete_post(request, post_pk):
    sections = Section.objects.all()
    post = Post.objects.get(id = post_pk)
    post.delete()

    return HttpResponseRedirect("/")

def update_post(request, post_pk):
    sections = Section.objects.all()
    post = Post.objects.get(id = post_pk)
    form = AdminPostForm(request.POST, instance = post)
    if request.method == "POST":
        if form.is_valid():
            form.save()

            return HttpResponseRedirect("/")
    else:
        form = AdminPostForm(instance = post)

    return render_to_response("blogs/blog_update_posts.html", {"sections": sections, "form": form}, context_instance = RequestContext(request))

practical_exam/templates/blogs/blog_add_post.html
{% extends "blogs/blog_base.html" %}

{% block head_title %}New Post{% endblock %}

{% block body %}
	<h2>Write New Post</h2>
    <div class="row blog-container">
        <form action='/add_post/' method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
        </form>
    </div>
{% endblock %}

practical_exam/templates/blogs/blog_base.html
{% extends "site_base.html" %}

{% block body_class %}blog{% endblock %}

{% block list %}
<ul class="dropdown-menu">    
    {% for section in sections %}
        <li><a href="{% url 'blog_section' section.slug %}">{{section.name}}</a></li>
    {% endfor %}
</ul>
{% endblock %}

{% block body %}
    <div class="row blog-container">
        <div class="col-md-3 sidebar">
            {% block sidebar %}
                <h1>
                    <a href="#">Author's Information</a>
                </h1>
                <p class="lead">
                    {{request.user.username}}<br>
                    {{request.user.first_name}}<br>
                    {{request.user.last_name}}<br>
                    {{request.user.email}}<br>
                    <p><a href="{% url 'add_post' %}">add new post</a> | <a href="{% url 'manage_posts' %}">manage posts</a></p>
            {% endblock %}
        </div>
        <div class="col-md-8 blog-content">
            {% block content %}{% endblock %}
        </div>
    </div>
{% endblock %}

practical_exam/templates/blogs/blog_contact_us.html
{% extends "blogs/blog_base.html" %}

{% block head_title %}Contact Us{% endblock %}

{% block body %}
	<h2>Contact Us</h2>
    <div class="row blog-container">
        <form action="{% url 'home' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
        </form>
    </div>
{% endblock %}

practical_exam/templates/blogs/blog_list.html
{% extends "blogs/blog_base.html" %}

{% block head_title %}{{ SITE_NAME }}{% endblock %}

{% block content %}
    {% if posts %}
        <div class="post-list">
            {% for post in posts %}
                <div class="post">
                    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                    {% include "blogs/dateline.html" %}
                    <div class="teaser">{{ post.teaser_html|safe }}</div>
                    <p class="more"><a href="{{ post.get_absolute_url }}" class="post-link">read more...</a></p>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No blog posts have been published.</p>
    {% endif %}
{% endblock %}

practical_exam/templates/blogs/blog_manage_posts.html
{% extends "blogs/blog_base.html" %}

{% block head_title %}{{ SITE_NAME }}{% endblock %}

{% block content %}
    {% if posts %}
        <div class="post-list">
        <p><a href="{% url 'home' %}">back</a></p>
            {% for post in posts %}
                <div class="post">
                    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                    {% include "blogs/dateline.html" %}
                    <div class="teaser">{{ post.teaser_html|safe }}</div>
                    <p><a href="{% url 'update_post' post.id%}">update post</a> | <a href="{% url 'delete_post' post.id %}">delete post</a></p>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No blog posts have been published.</p>
    {% endif %}
{% endblock %}

practical_exam/templates/blogs/blog_post.html
{% extends "blogs/blog_base.html" %}

{% block head_title %}{{ post.title }} &mdash; {{ SITE_NAME }}{% endblock %}

{% block extra_head %}
    <meta name="description" content="{{ post.teaser_html|striptags }}">
    <meta name="og:title" content="{{ post.title }}">
    <meta name="og:description" content="{{ post.teaser_html|striptags }}">
{% endblock %}

{% block content %}
    <div class="post-detail">
        <div class="post">
            <h1>{{ post.title }}</h1>
            {% include "blogs/dateline_stale.html" %}

            <div class="teaser">{{ post.teaser_html|safe }}</div>

            <div class="content">{{ post.content_html|safe }}</div>

            <div class="twitter-button">
                <a href="https://twitter.com/share" class="twitter-share-button" data-via="">Tweet</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            </div>
        </div>
    </div>
{% endblock %}

practical_exam/templates/blogs/blog_section_list.html
{% extends "blogs/blog_base.html" %}


{% block head_title %}{{ SITE_NAME }} ({{ section_name }}){% endblock %}

{% block content %}
    {% if posts %}
        <div class="post-list">
            {% for post in posts %}
                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                {% include "blogs/dateline.html" %}
                <div class="teaser">{{ post.teaser_html|safe }}</div>
                <p class="more"><a href="{{ post.get_absolute_url }}" class="post-link">read more...</a></p>
            {% endfor %}
        </div>
    {% else %}
        <p>No blog posts have been published in this section.</p>
    {% endif %}
{% endblock %}

practical_exam/templates/blogs/blog_sign_in.html
{% extends "blogs/blog_base.html" %}

{% block head_title %}Contact Us{% endblock %}

{% block body %}
	<h2>Login</h2>
    <div class="row blog-container">
        <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
        </form>
    </div>
{% endblock %}

practical_exam/templates/blogs/blog_sign_up.html
{% extends "blogs/blog_base.html" %}

{% block title %}Sign Up{% endblock %}

{% block body %}
	<h2>Sign Up</h2>
    <div class="row blog-container">
        <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
        </form>
    </div>
{% endblock %}

practical_exam/templates/blogs/blog_update_posts.html
{% extends "blogs/blog_base.html" %}

{% block head_title %}UpdatePost{% endblock %}

{% block body %}
	<h2>Update {{post.titlea}}</h2>
    <div class="row blog-container">
        <form action="{% url 'home' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
        </form>
    </div>
{% endblock %}

practical_exam/templates/blogs/dateline.html
<p class="post_dateline">
    <span class="date">{% if post.published %}{{ post.published|date:"jS F Y" }}{% else %}Not published yet{% endif %}</span>
    <br />
    by <span class="author"><a href="http://twitter.com/{{ post.author.username }}" title="@{{ post.author.username }}">{{ post.author.get_full_name }}</a></span> in
    <a href="{% url "blog_section" post.section.slug %}"><span class="section">{{ post.get_section_display|capfirst }}</span></a>
</p>

practical_exam/templates/blogs/dateline_stale.html
<p class="post_dateline">
    {% if not post.stale %}
        <span class="date">{% if post.published %}{{ post.published|date:"jS F Y" }}{% else %}Not published yet{% endif %}</span>
        <br />
    {% endif %}
    by <span class="author"><a href="http://twitter.com/{{ post.author.username }}" title="@{{ post.author.username }}">{{ post.author.get_full_name }}</a></span> in
    <a href="{% url "blog_section" post.section.slug %}"><span class="section">{{ post.get_section_display|capfirst }}</span></a>
</p>